### ISSUE TITLE
DESCRIPTION should also import numDeriv

### ISSUE THREAD

**Issue by jenzopr** [tallulandrews/M3D#1]
Dear Tallulah,

thanks for the nice package and the nice paper. During installation, numDeriv was additionally required for me. Maybe you can add it to the DESCRIPTION file in one of the next updates to smooth-en the installation process.

Best,
Jens

**Comment by tallulandrews** [comment]
Thanks for letting me know. It will be added in the next push.

Cheers,
Tallulah
